package com.example.jorge.gasolinator.BBDD.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.jorge.gasolinator.BBDD.db.Vehiculos;
import com.example.jorge.gasolinator.BBDD.db.Repostaje;
import com.example.jorge.gasolinator.BBDD.db.Impuestos;
import com.example.jorge.gasolinator.BBDD.db.Gastos;

import com.example.jorge.gasolinator.BBDD.db.VehiculosDao;
import com.example.jorge.gasolinator.BBDD.db.RepostajeDao;
import com.example.jorge.gasolinator.BBDD.db.ImpuestosDao;
import com.example.jorge.gasolinator.BBDD.db.GastosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig vehiculosDaoConfig;
    private final DaoConfig repostajeDaoConfig;
    private final DaoConfig impuestosDaoConfig;
    private final DaoConfig gastosDaoConfig;

    private final VehiculosDao vehiculosDao;
    private final RepostajeDao repostajeDao;
    private final ImpuestosDao impuestosDao;
    private final GastosDao gastosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        vehiculosDaoConfig = daoConfigMap.get(VehiculosDao.class).clone();
        vehiculosDaoConfig.initIdentityScope(type);

        repostajeDaoConfig = daoConfigMap.get(RepostajeDao.class).clone();
        repostajeDaoConfig.initIdentityScope(type);

        impuestosDaoConfig = daoConfigMap.get(ImpuestosDao.class).clone();
        impuestosDaoConfig.initIdentityScope(type);

        gastosDaoConfig = daoConfigMap.get(GastosDao.class).clone();
        gastosDaoConfig.initIdentityScope(type);

        vehiculosDao = new VehiculosDao(vehiculosDaoConfig, this);
        repostajeDao = new RepostajeDao(repostajeDaoConfig, this);
        impuestosDao = new ImpuestosDao(impuestosDaoConfig, this);
        gastosDao = new GastosDao(gastosDaoConfig, this);

        registerDao(Vehiculos.class, vehiculosDao);
        registerDao(Repostaje.class, repostajeDao);
        registerDao(Impuestos.class, impuestosDao);
        registerDao(Gastos.class, gastosDao);
    }
    
    public void clear() {
        vehiculosDaoConfig.clearIdentityScope();
        repostajeDaoConfig.clearIdentityScope();
        impuestosDaoConfig.clearIdentityScope();
        gastosDaoConfig.clearIdentityScope();
    }

    public VehiculosDao getVehiculosDao() {
        return vehiculosDao;
    }

    public RepostajeDao getRepostajeDao() {
        return repostajeDao;
    }

    public ImpuestosDao getImpuestosDao() {
        return impuestosDao;
    }

    public GastosDao getGastosDao() {
        return gastosDao;
    }

}
