package com.example.jorge.gasolinator.BBDD.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "REPOSTAJE".
 */
@Entity
public class Repostaje {

    @NotNull
    private String idVehiculo;

    @NotNull
    private String tipoLlenado;

    @NotNull
    private String kmActuales;

    @NotNull
    private String costeRepostaje;

    @NotNull
    private String litrosRepostaje;

    @NotNull
    private String precioLitroRepostaje;

    @NotNull
    private String diaRepostaje;

    @NotNull
    private String mesRepostaje;

    @NotNull
    private String añoRepostaje;
    private String foto_Uri;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Repostaje() {
    }

    @Generated
    public Repostaje(String idVehiculo, String tipoLlenado, String kmActuales, String costeRepostaje, String litrosRepostaje, String precioLitroRepostaje, String diaRepostaje, String mesRepostaje, String añoRepostaje, String foto_Uri) {
        this.idVehiculo = idVehiculo;
        this.tipoLlenado = tipoLlenado;
        this.kmActuales = kmActuales;
        this.costeRepostaje = costeRepostaje;
        this.litrosRepostaje = litrosRepostaje;
        this.precioLitroRepostaje = precioLitroRepostaje;
        this.diaRepostaje = diaRepostaje;
        this.mesRepostaje = mesRepostaje;
        this.añoRepostaje = añoRepostaje;
        this.foto_Uri = foto_Uri;
    }

    @NotNull
    public String getIdVehiculo() {
        return idVehiculo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdVehiculo(@NotNull String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    @NotNull
    public String getTipoLlenado() {
        return tipoLlenado;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTipoLlenado(@NotNull String tipoLlenado) {
        this.tipoLlenado = tipoLlenado;
    }

    @NotNull
    public String getKmActuales() {
        return kmActuales;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKmActuales(@NotNull String kmActuales) {
        this.kmActuales = kmActuales;
    }

    @NotNull
    public String getCosteRepostaje() {
        return costeRepostaje;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCosteRepostaje(@NotNull String costeRepostaje) {
        this.costeRepostaje = costeRepostaje;
    }

    @NotNull
    public String getLitrosRepostaje() {
        return litrosRepostaje;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLitrosRepostaje(@NotNull String litrosRepostaje) {
        this.litrosRepostaje = litrosRepostaje;
    }

    @NotNull
    public String getPrecioLitroRepostaje() {
        return precioLitroRepostaje;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPrecioLitroRepostaje(@NotNull String precioLitroRepostaje) {
        this.precioLitroRepostaje = precioLitroRepostaje;
    }

    @NotNull
    public String getDiaRepostaje() {
        return diaRepostaje;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDiaRepostaje(@NotNull String diaRepostaje) {
        this.diaRepostaje = diaRepostaje;
    }

    @NotNull
    public String getMesRepostaje() {
        return mesRepostaje;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMesRepostaje(@NotNull String mesRepostaje) {
        this.mesRepostaje = mesRepostaje;
    }

    @NotNull
    public String getAñoRepostaje() {
        return añoRepostaje;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAñoRepostaje(@NotNull String añoRepostaje) {
        this.añoRepostaje = añoRepostaje;
    }

    public String getFoto_Uri() {
        return foto_Uri;
    }

    public void setFoto_Uri(String foto_Uri) {
        this.foto_Uri = foto_Uri;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
