package com.example.jorge.gasolinator.BBDD.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "VEHICULOS".
 */
@Entity
public class Vehiculos {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String marca;

    @NotNull
    private String modelo;

    @NotNull
    private String apodo;

    @NotNull
    private String tipo;

    @NotNull
    private String combustible;

    @NotNull
    private String foto_Uri;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1024189188)
    public Vehiculos() {
    }

    public Vehiculos(Long id) {
        this.id = id;
    }

    @Generated(hash = 1841301493)
    public Vehiculos(Long id, @NotNull String marca, @NotNull String modelo, @NotNull String apodo, @NotNull String tipo,
            @NotNull String combustible, @NotNull String foto_Uri) {
        this.id = id;
        this.marca = marca;
        this.modelo = modelo;
        this.apodo = apodo;
        this.tipo = tipo;
        this.combustible = combustible;
        this.foto_Uri = foto_Uri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getMarca() {
        return marca;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMarca(@NotNull String marca) {
        this.marca = marca;
    }

    @NotNull
    public String getModelo() {
        return modelo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModelo(@NotNull String modelo) {
        this.modelo = modelo;
    }

    @NotNull
    public String getApodo() {
        return apodo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApodo(@NotNull String apodo) {
        this.apodo = apodo;
    }

    @NotNull
    public String getTipo() {
        return tipo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTipo(@NotNull String tipo) {
        this.tipo = tipo;
    }

    @NotNull
    public String getCombustible() {
        return combustible;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCombustible(@NotNull String combustible) {
        this.combustible = combustible;
    }

    @NotNull
    public String getFoto_Uri() {
        return foto_Uri;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFoto_Uri(@NotNull String foto_Uri) {
        this.foto_Uri = foto_Uri;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
